version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      env_file: .env  
    ports:
      - 4001:3000
    volumes:
      - /app/node_modules
      - D:/docker/frontend:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      env_file: .env  
    ports:
      - 4002:3000
    volumes:
      - /app/node_modules
      - D:/docker/frontend:/app
    command: ["npm","run","test"]  

